# This is a basic workflow to help you get started with Actions

name: Linting and Formatting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup
        run: npm ci
      - name: Formatting
        run: npm run format
      - name: Linting
        run: npm run lint
