name: Linting and Formatting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup
        run: npm install
      - name: Formatting
        continue-on-error: true
        run: npm run format
      - name: Linting
        run: npm run lint
